- name: Config keybindings for mag
  become_user: mag
  block:
    - name: Swap Caps Lock and Escape keys
      command: kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key Options caps:swapescape

      # So I can use this keybinding inside Jetbrains IDEs
    - name: Remove Ctrl+Alt+L Screen Lock keybinding
      command: kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group ksmserver --key 'Lock Session' 'Screensaver\tMeta+L,Meta+L\tCtrl+Alt+L\tScreensaver,Lock Session'


