- name: Disable systemdBoot
  # Has to be disabled to make the KDEWM config work
  # https://bugzilla.redhat.com/show_bug.cgi?id=1939291
  become: true
  lineinfile:
    path: /etc/xdg/startkderc
    regexp: '^systemdBoot='
    line: 'systemdBoot=false'
  when:
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version | int >= 34

- name: Add Plasma-i3 XSession
  become: true
  copy:
    src: plasma-i3.desktop
    dest: /usr/share/xsessions

- name: Swap Caps Lock and Escape keys
  become_user: mag
  lineinfile:
    path: ~/.config/kxkbrc
    regexp: "^Options="
    line: "Options=caps:swapescape"
