# Source: https://www.rust-lang.org/tools/install
- name: Install Rust
  become_user: mag
  shell:
    # -y switch needed for non-interactive installations
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    creates: ~/.cargo/bin/rustup

- name: Update Rust
  command: rustup update

- name: Install rust programs
  command:
    cmd: "cargo install {{ item.package }}"
    creates: "~/.cargo/bin/{{ item.binary }}"
  loop:
    - package: broot
      binary: broot
    - package: du-dust
      binary: dust
