---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Get distro variant
      set_fact:
        ansible_distribution_variant: "{{ lookup('ini', 'VARIANT_ID file=/etc/os-release type=properties') }}"
  roles:
    - name: fedora
      when: ansible_distribution == 'Fedora' and ansible_distribution_variant != 'silverblue'
    - name: silverblue
      when: ansible_distribution == 'Fedora' and ansible_distribution_variant == 'silverblue'
    - name: gnome
      when: ansible_env['XDG_CURRENT_DESKTOP'] == 'GNOME'
    - flatpak
    - git
    - gnupg
    - doas
    - bash
    - kitty
