---
- hosts: localhost
  connection: local
  roles:
    - name: macOS
      when: ansible_distribution == 'MacOSX'
    # - name: brew
      # when: ansible_distribution == 'MacOSX'
    - name: zsh
      when: ansible_distribution == 'MacOSX'
    - git
    - gnupg
    - neovim
