---
- hosts: localhost
  connection: local
#  vars_prompt:
#    - name: "user_password"
#      prompt: Enter a password for the user
#      private: true
#      encrypt: sha512_crypt
#      confirm: yes
  roles:
#    - kubeseal
#    - neofetch
#    - fish
#    - kitty
#    - nodejs
#    - rust
#    - python
#    - name: fedora
#      when: ansible_distribution == 'Fedora'
#    - snap
#    - flatpak
#    - git
#    - gnupg
#    - i3wm
#    - doas
#    - name: arch-linux
#      when: ansible_distribution == 'Arch Linux'
#    - name: kde
#      when: ansible_env['XDG_CURRENT_DESKTOP'] == 'KDE'
    - bash
    - name: gnome
      when: ansible_env['XDG_CURRENT_DESKTOP'] == 'GNOME'
#    - jetbrains-toolbox
#    - users
