- name: Add RPM Fusion repositories
  become: true
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Add Copr repositories
  command:
    cmd: dnf copr enable fuhrmann:i3-gaps
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:fuhrmann:i3-gaps.repo

- name: Add Google Cloud SDK yum repository
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    gpgcheck: true
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Add Hashicorp yum repository
  yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey:
      - https://rpm.releases.hashicorp.com/gpg

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
