- name: Add yum repositories
  become: true
  when: ansible_distribution == 'Fedora'
  block:
    - name: Add RPM Fusion repos
      dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
    - name: Add Copr repos
      command:
        cmd: dnf copr enable fuhrmann:i3-gaps
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:fuhrmann:i3-gaps.repo
    - name: Add Google Cloud SDK yum repository
      yum_repository:
        name: Google Cloud SDK
        description: "Repository for google cloud utilities. Source: https://cloud.google.com/sdk/docs/install"
        baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
        gpgcheck: true
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    - name: Add Hashicorp yum repository
      yum_repository:
        name: Hashicorp Stable - $basearch
        description: "Repository for Terraform and other Hashicorp products. Source: https://www.terraform.io/docs/cli/install/yum.html"
        baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey:
          - https://rpm.releases.hashicorp.com/gpg

- name: Install packages
  become: true
  dnf:
    update_cache: true
    state: latest
    name:
      - neovim
      - git
      - podman-docker
      - ripgrep
      - jq
      - bat
      - tealdeer
      - discord
      - exa
