- name: Symlink gpg-agent.conf
  file:
    src: "{{ role_path }}/files/gpg-agent.conf"
    dest: ~/.gnupg/gpg-agent.conf
    state: link
    force: true

- name: Symlink sshcontrol
  file:
    src: "{{ role_path }}/files/sshcontrol"
    dest: ~/.gnupg/sshcontrol
    state: link
    force: true
      

- name: Symlink ssh config
  file:
    src: "{{ role_path }}/files/ssh-config"
    dest: ~/.ssh/config
    state: link
    force: true