- name: Symlink gpg-agent.conf
  become_user: mag
  file:
    src: "{{ role_path }}/files/gpg-agent.conf"
    dest: ~/.gnupg/gpg-agent.conf
    state: link
    force: true

- name: Symlink sshcontrol
  become_user: mag
  file:
    src: "{{ role_path }}/files/sshcontrol"
    dest: ~/.gnupg/sshcontrol
    state: link
    force: true
