- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak packages
  community.general.flatpak:
    name:
    - Boxes
    - us.zoom.Zoom
    - com.discordapp.Discord
    - com.valvesoftware.Steam
    - com.spotify.Client
    state: present
