- name: Install kitty themes
  become_user: mag
  git:
    repo: https://github.com/dexpota/kitty-themes.git
    depth: 1
    dest: ~/.config/kitty/kitty-themes

- name: Set kitty color theme
  become_user: mag
  file:
    src: ~/.config/kitty/kitty-themes/themes/Monokai_Pro.conf
    dest: ~/.config/kitty/theme.conf
    state: link

- name: Symlink kitty.conf
  file:
    src: "{{ role_path }}/files/kitty.conf"
    dest: ~/.config/kitty/kitty.conf
    state: link