- name: Check if JetBrains Toolbox is installed
  stat:
    path: /usr/local/bin/jetbrains-toolbox
  register: toolbox

- name: Install JetBrains Toolbox
  when: not (toolbox.stat.exists and toolbox.stat.isreg)
  block:
    - name: Download toolbox
      get_url:
        url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.20.8804.tar.gz
        dest: /tmp/jetbrains-toolbox.tar.gz
      register: toolbox_download

    - name: Extract toolbox
      debugger: on_failed
      become: true
      unarchive:
        src: "{{ toolbox_download.dest }}"
        dest: /usr/local/bin/
        extra_opts:
          - --strip-components=1
